"""empty message

Revision ID: 2c8f043bd655
Revises: cbfeaf792d01
Create Date: 2024-05-03 21:51:30.462349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8f043bd655'
down_revision = 'cbfeaf792d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('following_username', sa.String(length=64), nullable=True))
        batch_op.drop_constraint('follow_following_key', type_='unique')
        batch_op.create_unique_constraint(None, ['following_username'])
        batch_op.drop_column('following')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('following', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('follow_following_key', ['following'])
        batch_op.drop_column('following_username')

    # ### end Alembic commands ###
