"""empty message

Revision ID: c6eb6d1bd9c8
Revises: bd8c1e4a66bb
Create Date: 2024-05-03 00:46:25.330578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6eb6d1bd9c8'
down_revision = 'bd8c1e4a66bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('follow')

    # ### end Alembic commands ###
