"""empty message

Revision ID: cbfeaf792d01
Revises: c6eb6d1bd9c8
Create Date: 2024-05-03 21:37:54.740757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbfeaf792d01'
down_revision = 'c6eb6d1bd9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('following', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('following')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('follow')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))

    op.drop_table('follow')
    # ### end Alembic commands ###
